apiVersion: batch/v1
kind: Job
metadata:
  name: jenkins
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: jenkins-trigger
        image: curlimages/curl
        env:
          - name: username
            valueFrom:
              secretKeyRef:
                name: jenkins-secret
                key: username
          - name: password
            valueFrom:
              secretKeyRef:
                name: jenkins-secret
                key: password
        args:
          - /bin/sh
          - -ec
          - {{ .Values.args.argue }}
      restartPolicy: Never
  backoffLimit: 0