apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ .Values.name }}-{{ .Values.env }}-tls"
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    venafi.cert-manager.io/custom-fields: '[{"name": "Owner", "value": "{{ .Values.certificateOwner }}"}]'
spec:
  commonName: "*.fraud-tech.{{ .Values.hostedZone }}"
  dnsNames:
  - "*.fraud-tech.{{ .Values.hostedZone }}"
  issuerRef:
    kind: ClusterIssuer
    name: venafi-issuer
  secretName: "{{ .Values.name }}-{{ .Values.env }}-https"
