apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Values.namePrefix }}{{ .Values.name }}-{{ .Values.env }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Values.namePrefix }}{{ .Values.name }}
    {{- if .Values.namePrefix }}
    feature: {{ trimSuffix "-" .Values.namePrefix }}
    {{- end}}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: {{ .Values.appPort }}
    - protocol: TCP
      port: {{ .Values.metricsPort }}
