{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: "{{ .Values.namePrefix }}{{ .Values.name }}-{{ .Values.env }}-secret"
  labels:
    app: {{ .Values.name }}
    {{- if .Values.namePrefix }}
    feature: {{ trimSuffix "-" .Values.namePrefix }}
    {{- end}}
type: Opaque
data:
{{ toYaml .Values.secrets | indent 2 }}
{{- end }}
