apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.namePrefix }}{{ .Values.name }}-{{ .Values.env }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Values.name }}
    {{- if .Values.namePrefix }}
    feature: {{trimSuffix "-" .Values.namePrefix }}
    {{- end}}
spec:
  selector:
    app: {{ .Values.name }}
    {{- if .Values.namePrefix }}
    feature: {{trimSuffix "-" .Values.namePrefix }}
    {{- end}}
  ports:
    - name: https
      port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
      protocol: TCP
    - name: metrics-port
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
      protocol: TCP
